/* 2:44:41 PM dss */ SHOW VARIABLES;
/* 2:44:41 PM dss */ SELECT @@global.max_allowed_packet;
/* 2:44:41 PM dss */ SHOW DATABASES;
/* 2:55:43 PM dss */ USE `world`;
/* 2:55:43 PM dss world */ SHOW VARIABLES LIKE 'character_set_database';
/* 2:55:43 PM dss world */ SHOW /*!50002 FULL*/ TABLES;
/* 2:55:43 PM dss world */ SELECT * FROM information_schema.routines WHERE routine_schema = 'world' ORDER BY routine_name;
/* 2:56:23 PM dss world */ select continent  from country;
/* 2:56:46 PM dss world */ select distinct(continent)  from country;
/* 2:57:16 PM dss world */ select name population from city;
/* 2:57:21 PM dss world */ select name, population from city;
/* 2:57:32 PM dss world */ select name, population from city where population > 1000000;
/* 2:57:48 PM dss world */ select name, population from city where population > 1000000 order by desc;
/* 3:10:14 PM dss world */ select name, population from city where population > 1000000 order by population desc;
/* 3:11:40 PM dss world */ select name, country, population from city where population between 8000000 and 10000000 order by population desc;
/* 3:11:55 PM dss world */ select name, countrycode, population from city where population between 8000000 and 10000000 order by population desc;
/* 3:12:38 PM dss world */ SHOW TABLE STATUS LIKE 'country';
/* 3:12:38 PM dss world */ SHOW CREATE TABLE `country`;
/* 3:12:38 PM dss world */ SET NAMES 'utf8mb4';
/* 3:12:38 PM dss world */ SELECT COUNT(1) FROM `country`;
/* 3:12:39 PM dss world */ SELECT * FROM `country` LIMIT 0,1000;
/* 3:12:39 PM dss world */ SHOW TABLES IN information_schema LIKE 'ENGINES';
/* 3:12:39 PM dss world */ SELECT Engine, Support FROM `information_schema`.`engines` WHERE SUPPORT IN ('DEFAULT', 'YES');
/* 3:12:39 PM dss world */ SELECT * FROM `information_schema`.`character_sets` ORDER BY `character_set_name` ASC;
/* 3:12:39 PM dss world */ SELECT * FROM `information_schema`.`collations` WHERE character_set_name = 'utf8mb4' ORDER BY `collation_name` ASC;
/* 3:12:47 PM dss world */ SELECT * FROM `country` ORDER BY `IndepYear` LIMIT 0,1000;
/* 3:12:48 PM dss world */ SELECT * FROM `country` ORDER BY `IndepYear` DESC LIMIT 0,1000;
/* 3:12:49 PM dss world */ SHOW INDEX FROM `country`;
/* 3:13:50 PM dss world */ select code, concat(name, IndepYear) as nameindep, contient, population from country;
/* 3:13:59 PM dss world */ select code, concat(name, IndepYear) as nameindep, continent, population from country;
/* 3:18:17 PM dss world */ select code, concat(name, IndepYear) as name(indep), continent, population from country where;
/* 3:18:52 PM dss world */ select code, concat(name, ,"(",IndepYear,")"), continent, population from country;
/* 3:19:03 PM dss world */ select code, concat(name, "(",IndepYear,")"), continent, population from country;
/* 3:19:26 PM dss world */ select code, concat(name, (,IndepYear,)), continent, population from country;
/* 3:21:12 PM dss world */ select code, concat(name, "(",IndepYear,")") as nameindep, continent, population from country;
/* 3:21:48 PM dss world */ select code, concat(name, "(",IndepYear,")") as nameindep, continent, population from country where indepyear between 1940 and 1950 order by population;
/* 3:24:00 PM dss world */ select countrycode, language, percentage from counrty;
/* 3:24:09 PM dss world */ select countrycode, language, percentage from countrylanguage;
/* 3:24:58 PM dss world */ select countrycode, language, percentage from countrylanguage where language in (korean,spanish,english);
/* 3:25:09 PM dss world */ select countrycode, language, percentage from countrylanguage where language in korean,spanish,english;
/* 3:26:10 PM dss world */ select countrycode, language, percentage from countrylanguage where percentage > 95 and language in ("korean",'spanish','english');
/* 3:28:21 PM dss world */ select countrycode, language, percentage from countrylanguage where percentage > 95 and language in ("korean",'spanish','english') order by percentage desc;
/* 3:30:41 PM dss world */ select code, name, continent, governmentform, population from country;
/* 3:31:14 PM dss world */ select code, name, continent, governmentform, population from country where name="a%";
/* 3:31:24 PM dss world */ select code, name, continent, governmentform, population from country where name="%a";
/* 3:31:33 PM dss world */ select code, name, continent, governmentform, population from country where name="$a";
/* 3:31:39 PM dss world */ select code, name, continent, governmentform, population from country where name="a$";
/* 3:32:17 PM dss world */ select code, name, continent, governmentform, population from country where name like "a$" and governmentform like "republic";
/* 3:32:26 PM dss world */ select code, name, continent, governmentform, population from country where name like "a$" and governmentform like "$republic$";
/* 3:32:55 PM dss world */ select code, name, continent, governmentform, population from country where name like "A$" and governmentform like "$Republic$";
/* 3:33:16 PM dss world */ select code, name, continent, governmentform, population from country where code like "A$" and governmentform like "$Republic$";
/* 3:33:17 PM dss world */ select code, name, continent, governmentform, population from country where code like "A$" and governmentform like "$Republic$";
/* 3:33:17 PM dss world */ select code, name, continent, governmentform, population from country where code like "A$" and governmentform like "$Republic$";
/* 3:33:18 PM dss world */ select code, name, continent, governmentform, population from country where code like "A$" and governmentform like "$Republic$";
/* 3:33:18 PM dss world */ select code, name, continent, governmentform, population from country where code like "A$" and governmentform like "$Republic$";
/* 3:33:18 PM dss world */ select code, name, continent, governmentform, population from country where code like "A$" and governmentform like "$Republic$";
/* 3:36:56 PM dss world */ select code, name, continent, governmentform, population from country where code like "A%" and governmentform like "%Republic%;
/* 3:38:19 PM dss world */ select code, name, continent, governmentform, population from country;
/* 3:38:33 PM dss world */ where code like "A%" and governmentform like "%Republic%";
/* 3:40:35 PM dss world */ select code, name, continent, governmentform, population from country where code like "A%" and governmentform like "%Republic%";
/* 3:43:07 PM dss world */ select count(continent) from country;
/* 3:43:25 PM dss world */ select count(distinct(continent)) from country;
/* 3:44:31 PM dss world */ select countinent, count(nation)  from country  group by countinent;
/* 3:44:53 PM dss world */ select countinent, count(name)  from country  group by countinent;
/* 3:45:06 PM dss world */ select continent, count(name)  from country  group by continent;
/* 3:47:49 PM dss world */ select countrycode, population from city;
/* 3:50:29 PM dss world */ select distinct(countrycode) as code, sum(population) as tp from city  group by code;
/* 3:50:37 PM dss world */ select distinct(countrycode) as code, sum(population) as tp from city  group by code  having tp desc;
/* 4:02:30 PM dss world */ select distinct(countrycode) as code, sum(population) as tp from city  group by code  having tp >50000000 order by tp desc;
/* 4:06:29 PM dss world */ select language, name from countrylanguage;
/* 4:06:49 PM dss world */ SET NAMES 'utf8';
/* 4:06:49 PM dss world */ SHOW TABLE STATUS LIKE 'countrylanguage';
/* 4:06:49 PM dss world */ SHOW CREATE TABLE `countrylanguage`;
/* 4:06:49 PM dss world */ SET NAMES 'utf8mb4';
/* 4:06:49 PM dss world */ SELECT COUNT(1) FROM `countrylanguage`;
/* 4:06:50 PM dss world */ SELECT * FROM `countrylanguage` LIMIT 0,1000;
/* 4:07:07 PM dss world */ select language, countrycode from countrylanguage;
/* 4:07:40 PM dss world */ select language, sum(countrycode) from countrylanguage group by language;
/* 4:08:15 PM dss world */ select language, sum(countrycode) as sum from countrylanguage group by language order by sum desc;
/* 4:08:52 PM dss world */ select language, sum(countrycode) as sum from countrylanguage group by language order by sum asc;
/* 4:09:04 PM dss world */ select language, sum(countrycode) as sum from countrylanguage group by language order by sum ascn;
/* 4:09:30 PM dss world */ select language, sum(countrycode) as sum from countrylanguage group by language order by sum desc;
/* 4:10:11 PM dss world */ SHOW INDEX FROM `countrylanguage`;
/* 4:11:11 PM dss world */ select language, count(countrycode) as sum from countrylanguage group by language order by sum desc;
/* 4:11:27 PM dss world */ select language, count(countrycode) as sum from countrylanguage group by language order by sum desc and limit 5,10;
/* 4:11:35 PM dss world */ select language, count(countrycode) as sum from countrylanguage group by language order by sum desc  limit 5,10;
/* 4:12:01 PM dss world */ select language, count(countrycode) as sum from countrylanguage group by language order by sum desc  limit 5;
/* 4:12:14 PM dss world */ select language, count(countrycode) as sum from countrylanguage group by language order by sum desc  limit 5,5;
/* 4:12:29 PM dss world */ select language, count(countrycode) as sum from countrylanguage group by language order by sum desc  limit 5,6;
